package main

import (
	"fmt"
	"log"
	"net"
	"net/http"
	"os"
	"runtime"
	"strings"
	"sync"
	"time"

	"github.com/HexmosTech/git-lrc/internal/naming"
	"github.com/urfave/cli/v2"
)

// Version information (set via ldflags during build)
const appVersion = "v0.1.43" // Semantic version - bump this for releases

var (
	version    = appVersion // Can be overridden via ldflags
	buildTime  = "unknown"
	gitCommit  = "unknown"
	reviewMode = "prod" // Set to "fake" by build-local-test via ldflags

	// Global review state for the web UI API
	currentReviewState *ReviewState
	reviewStateMu      sync.RWMutex
)

// Decision codes for interactive review flow.
const (
	decisionCommit = 0 // proceed with commit
	decisionAbort  = 1 // abort commit
	decisionSkip   = 2 // skip review, proceed with commit
	decisionVouch  = 4 // vouch for changes, proceed with commit
)

type interactivePhase int

const (
	phaseReviewRunning interactivePhase = iota
	phaseReviewComplete
)

func actionAllowedInPhase(code int, phase interactivePhase) bool {
	switch code {
	case decisionAbort:
		return true
	case decisionSkip, decisionVouch:
		return phase == phaseReviewRunning
	case decisionCommit:
		return phase == phaseReviewComplete
	default:
		return false
	}
}

type decisionRequestError struct {
	status  int
	message string
}

func (e *decisionRequestError) Error() string {
	return e.message
}

func validateInteractiveDecisionRequest(code int, message string, phase interactivePhase) error {
	if !actionAllowedInPhase(code, phase) {
		return &decisionRequestError{status: http.StatusConflict, message: "action not allowed in current review stage"}
	}
	if code == decisionCommit && strings.TrimSpace(message) == "" {
		return &decisionRequestError{status: http.StatusBadRequest, message: "commit message is required in web UI"}
	}
	return nil
}

func isFakeReviewBuild() bool {
	return strings.EqualFold(strings.TrimSpace(reviewMode), "fake")
}

func fakeReviewWaitDuration() (time.Duration, error) {
	raw := strings.TrimSpace(os.Getenv("LRC_FAKE_REVIEW_WAIT"))
	if raw == "" {
		return 30 * time.Second, nil
	}

	d, err := time.ParseDuration(raw)
	if err != nil {
		return 0, fmt.Errorf("invalid LRC_FAKE_REVIEW_WAIT %q: %w", raw, err)
	}
	if d <= 0 {
		return 0, fmt.Errorf("LRC_FAKE_REVIEW_WAIT must be > 0, got %q", raw)
	}
	return d, nil
}

func buildFakeSubmitResponse() diffReviewCreateResponse {
	ts := time.Now().UnixNano()
	return diffReviewCreateResponse{
		ReviewID:     fmt.Sprintf("fake-%d", ts),
		Status:       "queued",
		FriendlyName: naming.GenerateFriendlyName(),
	}
}

func buildFakeCompletedResult() *diffReviewResponse {
	return &diffReviewResponse{
		Status:  "completed",
		Summary: "# Fake Review Summary\n\nThis is a fake review generated by `build-local-test` for end-to-end testing.\n\n- No AI request was sent\n- No review comments were generated",
		Files:   []diffReviewFileResult{},
	}
}

func pollReviewFake(reviewID string, pollInterval, wait time.Duration, verbose bool, cancel <-chan struct{}) (*diffReviewResponse, error) {
	if pollInterval <= 0 {
		pollInterval = 1 * time.Second
	}

	start := time.Now()
	deadline := start.Add(wait)
	fmt.Printf("Waiting for fake review completion (poll every %s, delay %s)...\r\n", pollInterval, wait)
	syncFileSafely(os.Stdout)

	ticker := time.NewTicker(pollInterval)
	defer ticker.Stop()

	for {
		now := time.Now()
		if !now.Before(deadline) {
			statusLine := fmt.Sprintf("Status: completed | elapsed: %s", now.Sub(start).Truncate(time.Second))
			fmt.Printf("\r%-80s\r\n", statusLine)
			syncFileSafely(os.Stdout)
			if verbose {
				log.Printf("fake review %s completed", reviewID)
			}
			return buildFakeCompletedResult(), nil
		}

		statusLine := fmt.Sprintf("Status: in_progress | elapsed: %s", now.Sub(start).Truncate(time.Second))
		fmt.Printf("\r%-80s", statusLine)
		syncFileSafely(os.Stdout)
		if verbose {
			log.Printf("fake review %s: %s", reviewID, statusLine)
		}

		select {
		case <-cancel:
			fmt.Printf("\r\n")
			syncFileSafely(os.Stdout)
			return nil, errPollCancelled
		case <-ticker.C:
		}
	}
}

// diffReviewRequest models the POST payload to /api/v1/diff-review
type diffReviewRequest struct {
	DiffZipBase64 string `json:"diff_zip_base64"`
	RepoName      string `json:"repo_name"`
}

// diffReviewResponse models the response from GET /api/v1/diff-review/:id
type diffReviewResponse struct {
	Status       string                 `json:"status"`
	Summary      string                 `json:"summary,omitempty"`
	Files        []diffReviewFileResult `json:"files,omitempty"`
	Message      string                 `json:"message,omitempty"`
	FriendlyName string                 `json:"friendly_name,omitempty"`
}

type diffReviewCreateResponse struct {
	ReviewID     string `json:"review_id"`
	Status       string `json:"status"`
	FriendlyName string `json:"friendly_name,omitempty"`
	UserEmail    string `json:"user_email,omitempty"`
}

type APIError struct {
	StatusCode int
	Body       string
}

func (e *APIError) Error() string {
	return fmt.Sprintf("API returned status %d: %s", e.StatusCode, e.Body)
}

type diffReviewFileResult struct {
	FilePath string              `json:"file_path"`
	Hunks    []diffReviewHunk    `json:"hunks"`
	Comments []diffReviewComment `json:"comments"`
}

type diffReviewHunk struct {
	OldStartLine int    `json:"old_start_line"`
	OldLineCount int    `json:"old_line_count"`
	NewStartLine int    `json:"new_start_line"`
	NewLineCount int    `json:"new_line_count"`
	Content      string `json:"content"`
}

type diffReviewComment struct {
	Line     int    `json:"line"`
	Content  string `json:"content"`
	Severity string `json:"severity"`
	Category string `json:"category"`
}

const (
	defaultAPIURL       = "http://localhost:8888"
	defaultPollInterval = 2 * time.Second
	defaultTimeout      = 5 * time.Minute
	defaultOutputFormat = "pretty"
	commitMessageFile   = "livereview_commit_message"
	editorWrapperScript = "lrc_editor.sh"
	editorBackupFile    = ".lrc_editor_backup"
	pushRequestFile     = "livereview_push_request"

	// B2 constants for self-update (read-only credentials)
	b2KeyID      = "REDACTED_B2_KEY_ID"
	b2AppKey     = "REDACTED_B2_APP_KEY"
	b2BucketName = "hexmos"
	b2BucketID   = "33d6ab74ac456875919a0f1d"
	b2Prefix     = "lrc"
	b2AuthURL    = "https://api.backblazeb2.com/b2api/v2/b2_authorize_account"
)

// highlightURL adds ANSI color to make served links stand out in terminals.
func highlightURL(url string) string {
	return "\033[36m" + url + "\033[0m"
}

func buildReviewURL(apiURL, reviewID string) string {
	base := strings.TrimSuffix(strings.TrimSuffix(strings.TrimSuffix(apiURL, "/"), "/api"), "/api/v1")
	if base == "" {
		return ""
	}
	return fmt.Sprintf("%s/#/reviews/%s", base, reviewID)
}

var baseFlags = []cli.Flag{
	&cli.StringFlag{
		Name:    "repo-name",
		Usage:   "repository name (defaults to current directory basename)",
		EnvVars: []string{"LRC_REPO_NAME"},
	},
	&cli.BoolFlag{
		Name:    "staged",
		Usage:   "use staged changes instead of working tree",
		EnvVars: []string{"LRC_STAGED"},
	},
	&cli.StringFlag{
		Name:    "range",
		Usage:   "git range for staged/working diff override (e.g., HEAD~1..HEAD)",
		EnvVars: []string{"LRC_RANGE"},
	},
	&cli.StringFlag{
		Name:    "commit",
		Usage:   "review a specific commit or commit range (e.g., HEAD, HEAD~1, HEAD~3..HEAD, abc123)",
		EnvVars: []string{"LRC_COMMIT"},
	},
	&cli.StringFlag{
		Name:    "diff-file",
		Usage:   "path to pre-generated diff file",
		EnvVars: []string{"LRC_DIFF_FILE"},
	},
	&cli.StringFlag{
		Name:    "api-url",
		Value:   defaultAPIURL,
		Usage:   "LiveReview API base URL",
		EnvVars: []string{"LRC_API_URL"},
	},
	&cli.StringFlag{
		Name:    "api-key",
		Usage:   "API key for authentication (can be set in ~/.lrc.toml or env var)",
		EnvVars: []string{"LRC_API_KEY"},
	},
	&cli.StringFlag{
		Name:    "output",
		Value:   defaultOutputFormat,
		Usage:   "output format: pretty or json",
		EnvVars: []string{"LRC_OUTPUT"},
	},
	&cli.StringFlag{
		Name:    "save-html",
		Usage:   "save formatted HTML output (GitHub-style review) to this file",
		EnvVars: []string{"LRC_SAVE_HTML"},
	},
	&cli.BoolFlag{
		Name:    "serve",
		Usage:   "start HTTP server to serve the HTML output (auto-creates HTML when omitted)",
		EnvVars: []string{"LRC_SERVE"},
	},
	&cli.IntFlag{
		Name:    "port",
		Usage:   "port for HTTP server (used with --serve)",
		Value:   8000,
		EnvVars: []string{"LRC_PORT"},
	},
	&cli.BoolFlag{
		Name:    "verbose",
		Usage:   "enable verbose output",
		EnvVars: []string{"LRC_VERBOSE"},
	},
	&cli.BoolFlag{
		Name:    "precommit",
		Usage:   "pre-commit mode: interactive prompts for commit decision (Ctrl-C=abort, Ctrl-S=skip+commit, Ctrl-V=vouch+commit, Enter=commit)",
		Value:   false,
		EnvVars: []string{"LRC_PRECOMMIT"},
	},
	&cli.BoolFlag{
		Name:    "skip",
		Usage:   "mark review as skipped and write attestation without contacting the API",
		EnvVars: []string{"LRC_SKIP"},
	},
	&cli.BoolFlag{
		Name:    "force",
		Usage:   "force rerun by removing existing attestation/hash for current tree",
		EnvVars: []string{"LRC_FORCE"},
	},
	&cli.BoolFlag{
		Name:    "vouch",
		Usage:   "vouch for changes manually without running AI review (records attestation with coverage stats from prior iterations)",
		EnvVars: []string{"LRC_VOUCH"},
	},
}

var debugFlags = []cli.Flag{
	&cli.StringFlag{
		Name:    "diff-source",
		Usage:   "diff source: working, staged, range, or file (debug override)",
		EnvVars: []string{"LRC_DIFF_SOURCE"},
		Hidden:  true,
	},
	&cli.DurationFlag{
		Name:    "poll-interval",
		Value:   defaultPollInterval,
		Usage:   "interval between status polls",
		EnvVars: []string{"LRC_POLL_INTERVAL"},
	},
	&cli.DurationFlag{
		Name:    "timeout",
		Value:   defaultTimeout,
		Usage:   "maximum time to wait for review completion",
		EnvVars: []string{"LRC_TIMEOUT"},
	},
	&cli.StringFlag{
		Name:    "save-bundle",
		Usage:   "save the base64-encoded bundle to this file for inspection before sending",
		EnvVars: []string{"LRC_SAVE_BUNDLE"},
	},
	&cli.StringFlag{
		Name:    "save-json",
		Usage:   "save the JSON response to this file after completion",
		EnvVars: []string{"LRC_SAVE_JSON"},
	},
	&cli.StringFlag{
		Name:    "save-text",
		Usage:   "save formatted text output with comment markers to this file",
		EnvVars: []string{"LRC_SAVE_TEXT"},
	},
}

func main() {
	app := &cli.App{
		Name:    "lrc",
		Usage:   "LiveReview CLI - submit local diffs for AI review",
		Version: version,
		Flags:   baseFlags,
		Commands: []*cli.Command{
			{
				Name:    "review",
				Aliases: []string{"r"},
				Usage:   "Run a review with sensible defaults",
				Flags:   baseFlags,
				Action:  runReviewSimple,
			},
			{
				Name:   "review-debug",
				Usage:  "Run a review with advanced debug options",
				Flags:  append(baseFlags, debugFlags...),
				Action: runReviewDebug,
			},
			{
				Name:  "hooks",
				Usage: "Manage LiveReview Git hook integration (global dispatcher)",
				Subcommands: []*cli.Command{
					{
						Name:  "install",
						Usage: "Install global LiveReview hook dispatchers (uses core.hooksPath)",
						Flags: []cli.Flag{
							&cli.StringFlag{
								Name:  "path",
								Usage: "custom hooksPath (defaults to core.hooksPath or ~/.git-hooks)",
							},
							&cli.BoolFlag{
								Name:  "local",
								Usage: "install into the current repo hooks path (respects core.hooksPath)",
							},
						},
						Action: runHooksInstall,
					},
					{
						Name:  "uninstall",
						Usage: "Remove LiveReview hook dispatchers and managed scripts",
						Flags: []cli.Flag{
							&cli.BoolFlag{
								Name:  "local",
								Usage: "uninstall from the current repo hooks path",
							},
							&cli.StringFlag{
								Name:  "path",
								Usage: "target a specific hooksPath directory for uninstall",
							},
						},
						Action: runHooksUninstall,
					},
					{
						Name:   "enable",
						Usage:  "Enable LiveReview hooks for the current repository",
						Action: runHooksEnable,
					},
					{
						Name:   "disable",
						Usage:  "Disable LiveReview hooks for the current repository",
						Action: runHooksDisable,
					},
					{
						Name:   "status",
						Usage:  "Show LiveReview hook status for the current repository",
						Action: runHooksStatus,
					},
				},
			},
			{
				Name:   "install-hooks",
				Usage:  "Install LiveReview hooks (deprecated; use 'lrc hooks install')",
				Hidden: true,
				Action: runHooksInstall,
			},
			{
				Name:   "uninstall-hooks",
				Usage:  "Uninstall LiveReview hooks (deprecated; use 'lrc hooks uninstall')",
				Hidden: true,
				Action: runHooksUninstall,
			},
			{
				Name:  "version",
				Usage: "Show version information",
				Action: func(c *cli.Context) error {
					fmt.Printf("lrc version %s\n", version)
					fmt.Printf("  Build time: %s\n", buildTime)
					fmt.Printf("  Git commit: %s\n", gitCommit)
					return nil
				},
			},
			{
				Name:    "self-update",
				Aliases: []string{"update"},
				Usage:   "Update lrc to the latest version",
				Flags: []cli.Flag{
					&cli.BoolFlag{
						Name:  "check",
						Usage: "Only check for updates without installing",
					},
					&cli.BoolFlag{
						Name:  "force",
						Usage: "Force recovery by terminating another active lrc self-update process, then continue update",
					},
				},
				Action: runSelfUpdate,
			},
			{
				Name:   "review-cleanup",
				Usage:  "Clean up review session history for the current branch (called by post-commit hook)",
				Hidden: true,
				Flags: []cli.Flag{
					&cli.BoolFlag{
						Name:  "verbose",
						Usage: "enable verbose output",
					},
				},
				Action: func(c *cli.Context) error {
					return runReviewDBCleanup(c.Bool("verbose"))
				},
			},
			{
				Name:   "attestation-trailer",
				Usage:  "Output the commit trailer for the current attestation (called by commit-msg hook)",
				Hidden: true,
				Action: runAttestationTrailer,
			},
			{
				Name:   "setup",
				Usage:  "Guided onboarding — authenticate with Hexmos and configure LiveReview + AI",
				Action: runSetup,
			},
			{
				Name:   "ui",
				Usage:  "Open local web UI to manage your git-lrc",
				Action: runUI,
			},
		},
		Action: runReviewSimple,
	}

	if err := app.Run(os.Args); err != nil {
		log.Fatal(err)
	}
}

type reviewOptions struct {
	repoName     string
	diffSource   string
	rangeVal     string
	commitVal    string
	diffFile     string
	apiURL       string
	apiKey       string
	pollInterval time.Duration
	timeout      time.Duration
	output       string
	saveBundle   string
	saveJSON     string
	saveText     string
	saveHTML     string
	serve        bool
	port         int
	verbose      bool
	precommit    bool
	skip         bool
	force        bool
	vouch        bool
	initialMsg   string
}

func runReviewSimple(c *cli.Context) error {
	opts, err := buildOptionsFromContext(c, false)
	if err != nil {
		return err
	}
	return runReviewWithOptions(opts)
}

func runReviewDebug(c *cli.Context) error {
	opts, err := buildOptionsFromContext(c, true)
	if err != nil {
		return err
	}
	return runReviewWithOptions(opts)
}

func buildOptionsFromContext(c *cli.Context, includeDebug bool) (reviewOptions, error) {
	// Get initial commit message from file or environment variable
	initialMsg := ""
	if msgFile := os.Getenv("LRC_INITIAL_MESSAGE_FILE"); msgFile != "" {
		if data, err := os.ReadFile(msgFile); err == nil {
			initialMsg = strings.TrimRight(string(data), "\r\n")
		}
	} else {
		initialMsg = strings.TrimRight(os.Getenv("LRC_INITIAL_MESSAGE"), "\r\n")
	}

	opts := reviewOptions{
		repoName:   c.String("repo-name"),
		rangeVal:   c.String("range"),
		commitVal:  c.String("commit"),
		diffFile:   c.String("diff-file"),
		apiURL:     c.String("api-url"),
		apiKey:     c.String("api-key"),
		output:     c.String("output"),
		saveHTML:   c.String("save-html"),
		serve:      c.Bool("serve"),
		port:       c.Int("port"),
		verbose:    c.Bool("verbose"),
		precommit:  c.Bool("precommit"),
		skip:       c.Bool("skip"),
		force:      c.Bool("force"),
		vouch:      c.Bool("vouch"),
		saveJSON:   c.String("save-json"),
		saveText:   c.String("save-text"),
		initialMsg: initialMsg,
	}

	if opts.skip || opts.vouch {
		opts.precommit = false
	}
	if opts.skip && opts.vouch {
		return reviewOptions{}, fmt.Errorf("cannot use --skip and --vouch together")
	}

	staged := c.Bool("staged")
	diffSource := c.String("diff-source")

	if opts.diffFile != "" {
		diffSource = "file"
	} else if opts.commitVal != "" {
		diffSource = "commit"
		// Commit mode is for post-commit reviews - disable precommit/skip features
		opts.precommit = false
		opts.skip = false
		// Auto-enable serve mode for post-commit reviews (user can view in browser)
		// Only if not explicitly set by user via flags
		if !c.IsSet("serve") && !c.IsSet("save-html") {
			opts.serve = true
		}
	} else if opts.rangeVal != "" {
		diffSource = "range"
	} else if staged {
		diffSource = "staged"
	}

	if diffSource == "" {
		diffSource = "staged"
	}

	opts.diffSource = diffSource

	if includeDebug {
		opts.pollInterval = c.Duration("poll-interval")
		opts.timeout = c.Duration("timeout")
		opts.saveBundle = c.String("save-bundle")
	} else {
		opts.pollInterval = defaultPollInterval
		opts.timeout = defaultTimeout
	}

	if opts.apiURL == "" {
		opts.apiURL = defaultAPIURL
	}

	if opts.output == "" {
		opts.output = defaultOutputFormat
	}

	return opts, nil
}

// applyDefaultHTMLServe enables HTML saving/serving when the user runs with defaults.
// It only triggers when no HTML path or serve flag was provided and the output format is the default.
func applyDefaultHTMLServe(opts *reviewOptions) (string, error) {
	// If HTML path already set or output format is not HTML, nothing to do
	if opts.saveHTML != "" || opts.output != defaultOutputFormat {
		return opts.saveHTML, nil
	}

	// Serve is enabled but no HTML path - create temp file
	if opts.serve {
		tmpFile, err := os.CreateTemp("", "lrc-review-*.html")
		if err != nil {
			return "", fmt.Errorf("failed to create temporary HTML file: %w", err)
		}

		if err := tmpFile.Close(); err != nil {
			return "", fmt.Errorf("failed to prepare temporary HTML file: %w", err)
		}

		opts.saveHTML = tmpFile.Name()
		return opts.saveHTML, nil
	}

	return "", nil
}

// pickServePort tries the requested port, then increments by 1 up to maxTries to find a free port.
// It returns the listener itself (kept open) to avoid TOCTOU races where another
// process grabs the port between the check and the actual server start.
//
// On Windows, 0.0.0.0:<port> and 127.0.0.1:<port> are treated as separate bindings,
// so we must check both to detect if a port is truly occupied. On Linux/Mac,
// binding 0.0.0.0 already conflicts with 127.0.0.1, so a single check suffices.
func pickServePort(preferredPort, maxTries int) (net.Listener, int, error) {
	for i := 0; i < maxTries; i++ {
		candidate := preferredPort + i

		if runtime.GOOS == "windows" {
			// On Windows, check both addresses. If either is occupied, the port is busy.
			lnLocal, errLocal := net.Listen("tcp", fmt.Sprintf("127.0.0.1:%d", candidate))
			lnAll, errAll := net.Listen("tcp", fmt.Sprintf("0.0.0.0:%d", candidate))

			if errLocal != nil || errAll != nil {
				// Port is busy on at least one address — close whichever succeeded
				if lnLocal != nil {
					lnLocal.Close()
				}
				if lnAll != nil {
					lnAll.Close()
				}
				continue
			}

			// Both succeeded — port is free. Close the 0.0.0.0 listener,
			// keep 127.0.0.1 (lrc only serves on localhost).
			lnAll.Close()
			return lnLocal, candidate, nil
		}

		// Linux/Mac: single bind on all interfaces is sufficient
		ln, err := net.Listen("tcp", fmt.Sprintf(":%d", candidate))
		if err == nil {
			return ln, candidate, nil
		}
	}

	return nil, 0, fmt.Errorf("no available port found starting from %d", preferredPort)
}

// GIT HOOK MANAGEMENT
// =============================================================================

const (
	lrcMarkerBegin        = "# BEGIN lrc managed section - DO NOT EDIT"
	lrcMarkerEnd          = "# END lrc managed section"
	defaultGlobalHooksDir = ".git-hooks"
	hooksMetaFilename     = ".lrc-hooks-meta.json"
)

var managedHooks = []string{"pre-commit", "prepare-commit-msg", "commit-msg", "post-commit"}
