package main

import (
	"bytes"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"strconv"
	"strings"
)

func decodeJWTClaims(jwt string) map[string]string {
	claims := map[string]string{}
	parts := strings.Split(jwt, ".")
	if len(parts) < 2 {
		return claims
	}

	payload, err := base64.RawURLEncoding.DecodeString(parts[1])
	if err != nil {
		return claims
	}

	parsed := map[string]interface{}{}
	if err := json.Unmarshal(payload, &parsed); err != nil {
		return claims
	}

	for key, value := range parsed {
		if text, ok := value.(string); ok {
			claims[key] = strings.TrimSpace(text)
		}
	}

	return claims
}

func firstNonEmpty(values ...string) string {
	for _, value := range values {
		if trimmed := strings.TrimSpace(value); trimmed != "" {
			return trimmed
		}
	}
	return ""
}

func buildLiveReviewURL(baseURL, apiPath string) string {
	base := strings.TrimRight(strings.TrimSpace(baseURL), "/")
	base = strings.TrimSuffix(base, "/api/v1")
	base = strings.TrimSuffix(base, "/api")
	return base + apiPath
}

func writeRawJSON(w http.ResponseWriter, status int, body []byte) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	if _, err := io.Copy(w, bytes.NewReader(body)); err != nil {
		log.Printf("failed to write JSON response (status=%d): %v", status, err)
	}
}

func writeJSONError(w http.ResponseWriter, status int, message string) {
	writeRawJSON(w, status, []byte(fmt.Sprintf(`{"error":%q}`, message)))
}

func writeJSON(w http.ResponseWriter, status int, payload interface{}) {
	body, err := json.Marshal(payload)
	if err != nil {
		writeJSONError(w, http.StatusInternalServerError, "failed to encode response")
		return
	}
	writeRawJSON(w, status, body)
}

func upsertQuotedConfigValue(content string, key string, value string) string {
	lines := strings.Split(content, "\n")
	prefix := key + " = "
	replacement := prefix + strconv.Quote(value)
	replaced := false

	for i, line := range lines {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, prefix) {
			lines[i] = replacement
			replaced = true
			break
		}
	}

	if !replaced {
		if len(lines) > 0 && strings.TrimSpace(lines[len(lines)-1]) != "" {
			lines = append(lines, "")
		}
		lines = append(lines, replacement)
	}

	return strings.Join(lines, "\n")
}

func stripManagedAIConnectorsSection(content string) string {
	start := strings.Index(content, aiConnectorsSectionBegin)
	if start == -1 {
		return content
	}

	endRelative := strings.Index(content[start:], aiConnectorsSectionEnd)
	if endRelative == -1 {
		return content[:start]
	}

	end := start + endRelative + len(aiConnectorsSectionEnd)
	if end < len(content) {
		if content[end] == '\r' {
			end++
		}
		if end < len(content) && content[end] == '\n' {
			end++
		}
	}

	return content[:start] + content[end:]
}

func renderManagedAIConnectorsSection(connectors []aiConnectorRemote) string {
	var builder strings.Builder
	builder.WriteString(aiConnectorsSectionBegin)
	builder.WriteString("\n")
	builder.WriteString("# Generated by lrc ui. This section is auto-managed and will be replaced.\n")

	for _, connector := range connectors {
		builder.WriteString("\n[[ai_connectors]]\n")
		builder.WriteString("id = ")
		builder.WriteString(strconv.FormatInt(connector.ID, 10))
		builder.WriteString("\n")
		builder.WriteString("provider_name = ")
		builder.WriteString(strconv.Quote(connector.ProviderName))
		builder.WriteString("\n")
		builder.WriteString("connector_name = ")
		builder.WriteString(strconv.Quote(connector.ConnectorName))
		builder.WriteString("\n")
		builder.WriteString("api_key = ")
		builder.WriteString(strconv.Quote(connector.APIKey))
		builder.WriteString("\n")
		if connector.BaseURL != "" {
			builder.WriteString("base_url = ")
			builder.WriteString(strconv.Quote(connector.BaseURL))
			builder.WriteString("\n")
		}
		if connector.SelectedModel != "" {
			builder.WriteString("selected_model = ")
			builder.WriteString(strconv.Quote(connector.SelectedModel))
			builder.WriteString("\n")
		}
		builder.WriteString("display_order = ")
		builder.WriteString(strconv.Itoa(connector.DisplayOrder))
		builder.WriteString("\n")
		if connector.CreatedAt != "" {
			builder.WriteString("created_at = ")
			builder.WriteString(strconv.Quote(connector.CreatedAt))
			builder.WriteString("\n")
		}
		if connector.UpdatedAt != "" {
			builder.WriteString("updated_at = ")
			builder.WriteString(strconv.Quote(connector.UpdatedAt))
			builder.WriteString("\n")
		}
	}

	builder.WriteString("\n")
	builder.WriteString(aiConnectorsSectionEnd)
	return builder.String()
}
