package storage

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"strings"
)

const (
	lrcInstallerCommentLine        = "# Added by lrc installer"
	lrcInstallerEnvPathMarker      = ".lrc/env"
	lrcInstallerSourcePrefixDot    = "."
	lrcInstallerSourcePrefixSource = "source"
	lrcInstallerFishManagedMarker  = "lrc shell setup (auto-generated by lrc installer)"
	lineEndingLF                   = "\n"
	lineEndingCRLF                 = "\r\n"
)

// RemoveFileIfExists removes a file when present and reports whether it existed.
func RemoveFileIfExists(path string, dryRun bool) (bool, error) {
	if dryRun {
		if _, err := os.Stat(path); err != nil {
			if os.IsNotExist(err) {
				return false, nil
			}
			return false, fmt.Errorf("failed to stat file %s: %w", path, err)
		}
		return true, nil
	}

	if err := Remove(path); err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			return false, nil
		}
		return false, fmt.Errorf("failed to remove file %s: %w", path, err)
	}
	return true, nil
}

// RemoveLRCInstallerShellSourceLines removes installer-added lrc source lines from an rc file.
func RemoveLRCInstallerShellSourceLines(path string, dryRun bool) (bool, error) {
	content, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, fmt.Errorf("failed to read shell rc file %s: %w", path, err)
	}

	raw := string(content)
	lineEnding := lineEndingLF
	if strings.Contains(raw, lineEndingCRLF) {
		lineEnding = lineEndingCRLF
	}

	lines := strings.Split(raw, lineEnding)

	out := make([]string, 0, len(lines))
	changed := false

	for i := 0; i < len(lines); i++ {
		trimmed := strings.TrimSpace(lines[i])

		if trimmed == lrcInstallerCommentLine {
			nextLineIndex := i + 1
			if nextLineIndex < len(lines) && isLRCInstallerSourceLine(lines[nextLineIndex]) {
				changed = true
				i++
				continue
			}
		}

		if isLRCInstallerSourceLine(lines[i]) {
			changed = true
			continue
		}

		out = append(out, lines[i])
	}

	if !changed {
		return false, nil
	}

	if dryRun {
		return true, nil
	}

	if err := WriteFile(path, []byte(strings.Join(out, lineEnding)), 0644); err != nil {
		return false, fmt.Errorf("failed to update shell rc file %s: %w", path, err)
	}

	return true, nil
}

// RemoveManagedFishLRCConfig removes the fish lrc config when it is installer-managed.
func RemoveManagedFishLRCConfig(path string, dryRun bool) (bool, error) {
	content, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, fmt.Errorf("failed to read fish config %s: %w", path, err)
	}

	if !strings.Contains(string(content), lrcInstallerFishManagedMarker) {
		return false, nil
	}

	if dryRun {
		return true, nil
	}

	if err := Remove(path); err != nil {
		return false, fmt.Errorf("failed to remove fish config %s: %w", path, err)
	}
	return true, nil
}

// RemoveDirIfEmptyIfExists removes a directory only when it is empty.
func RemoveDirIfEmptyIfExists(path string, dryRun bool) (bool, error) {
	entries, err := os.ReadDir(path)
	if err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			return false, nil
		}
		return false, fmt.Errorf("failed to read directory %s: %w", path, err)
	}

	if len(entries) != 0 {
		return false, nil
	}

	if dryRun {
		return true, nil
	}

	if err := Remove(path); err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			return false, nil
		}
		return false, fmt.Errorf("failed to remove empty directory %s: %w", path, err)
	}
	return true, nil
}

func isLRCInstallerSourceLine(line string) bool {
	trimmed := strings.TrimSpace(line)
	if !strings.Contains(trimmed, lrcInstallerEnvPathMarker) {
		return false
	}
	if !strings.HasPrefix(trimmed, lrcInstallerSourcePrefixDot) && !strings.HasPrefix(trimmed, lrcInstallerSourcePrefixSource) {
		return false
	}
	return true
}
